# GitHub Actions Workflow for testing and building the plugin
name: Run Unit Tests and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build # This is also going to run the unit tests
